apiVersion: v1
kind: ConfigMap

metadata:
  name: board-config

data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: 10.0.3.4:9092
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATA_REDIS_HOST: 10.0.3.138
  SPRING_DATA_REDIS_PORT: "6379"
  USER_SERVICE_URL: http://user-service:8080
  POINT_SERVICE_URL: http://point-service:8082
